### PR TITLE
Fix Gtk.ProgressBar API call

### PR DESCRIPTION
**Pull request by cydanil**
A quick one: to delete a recipe, it first goes to the trash, then said trash can be emptied.

When attempting the empty it, a progress bar is drawn, and had an outdated API call.
With these changes, the deletion functionality fully works as expected.

### CODE REVIEW

**Review by maweki — APPROVED** [review]

**Comment by kirienko** [comment]
LGTM!

A side question: do you really see a progress bar? I don't see any, neither in the master nor in your branch. Maybe the deletion process is too fast for that.

**Comment by kirienko** [comment]
I also noticed a GUI bug, which goes beyond this PR:

image

The content is mostly hidden, because the inner part of the window is not expanded. I saw the same in #97. There I worked around that by changing `Gtk.PolicyType`. But probably that's not a best solution.

**Comment by cydanil** [comment]
Ok, I use XFCE, and I get a scrollbar:

image

I agree that it would be nice that the widget resize with the window. I can do it in this PR if you like.

**Comment by kirienko** [comment]
I'd say it's better to fix that separately, to emphasize the problem. This PR looks ready. [I just wanted to figure out if this bug is Gnome-related.]

**Comment by cydanil** [comment]
Thanks for having a look!

**Pull request merged**
