### PR TITLE
Chg: install 'pygtkspellcheck' in CI for tests

### PR DESCRIPTION
**Pull request by saxon-s**
Uncommenting 'pygtkspellcheck' in requirements.txt will allow the library to
be installed in the CI and enable spellcheck plugin test to successfully run.

'pygtkspellcheck' was commented out in commit #19 as Windows had some
challenges.

The current Python 3 migration is focused on Linux. CI install issues on
Windows and other platforms will need to be addressed later.

### CODE REVIEW

**Comment by cydanil** [comment]
You also need to install `enchant` :)

**Comment by saxon-s** [comment]
> You also need to install `enchant` :)

I see there is an `apt-get install enchant` instruction in the `Install Ubuntu dependencies` section of `build.yml` and `tests.yml`. From the log file, it appears `enchant` gets installed. However it fails when `pip install pygstspellcheck` is attempted. As you mention above, `enchant` needs to be installed. But where? I added an additional ` sudo apt-get install enchant` in the `Install dependencies` section and get, as expected `enchant is already the newest version (1.6.0-11.3build1)`.

**Comment by takluyver** [comment]
The `enchant` package in Ubuntu is probably the command line tool. We likely want [python3-enchant](https://packages.ubuntu.com/focal/python3-enchant) from apt, or [pyenchant](https://pypi.org/project/pyenchant/) from PyPI, assuming that's the same thing.

**Comment by saxon-s** [comment]
> The `enchant` package in Ubuntu is probably the command line tool. We likely want [python3-enchant](https://packages.ubuntu.com/focal/python3-enchant) from apt, or [pyenchant](https://pypi.org/project/pyenchant/) from PyPI, assuming that's the same thing.

You are correct, `python3-enchant` needs to be apt installed. `pyenchant` is pip installed with `requirements.txt`. Thanks.

**Comment by takluyver** [comment]
I think that got rid of the gtkspellcheck error in the tests. :+1:

**Comment by cydanil** [comment]
Very nice, thanks a lot :)

**Pull request merged**
