### PR TITLE
Fix settings lineage

### PR DESCRIPTION
**Pull request by kirienko**
This fixes adding a lot of extra newlines during simple changes in `settings.py` during  the installation process (spotted by @maweki).

The problem was that by default print function obviously adds an extra `\n` in the end.

I also changed the `inplace` parameter from `1` to `True` for sake of readability.

### CODE REVIEW

**Comment by kirienko** [comment]
Hold on a second, why it breaks our build now?

**Comment by maweki** [comment]
Is this really best practice for coding paths during setup? I'd guess not. If we want to throw this part of the setup out and replace it by something somewhat maintainable, I am all in favor of it.

**Comment by kirienko** [comment]
@maweki I fully agree that this way of doing things might not be obvious. But python packaging is rather strange thing by itself, and we need to have at least something for right now. This doesn't fix #107 of course but this will do the installation a tiny bit less ugly.

Maybe we can kindly ask @takluyver to tell us about best practices :smirk:

**Comment by takluyver** [comment]
I think this looks OK as a small fix for a small issue.

I'm not aware of any best practice for this kind of thing. Python packaging is mostly designed around delivering libraries rather than applications, and the general pattern is that anything your code wants to access at runtime is delivered inside the package folder, and accessed using a relative path, e.g. with [importlib.resources](https://docs.python.org/3/library/importlib.html#module-importlib.resources).

Python packaging has moved away from running `setup.py install`: pip will now try to use a wheel, and if one isn't available, it will run `setup.py bdist_wheel` to make a wheel, and then install from that. This is important because the build step doesn't know where the package will be installed. And installing a wheel doesn't run any code from that wheel. In short, this approach of rewriting paths at install time is doomed.

**Comment by maweki** [comment]
> In short, this approach of rewriting paths at install time is doomed.

Doomed and unmaintainable. Is there a way we can do it with relative paths? What would we need to do to fix this?

**Comment by kirienko** [comment]
BTW I tried to install `gourmet` from the package created by `python setup.py bdist`, and it didn't help either.

**Comment by kirienko** [comment]
Thank you Thomas!
If there's no other objections, I would merge this small fix and, I'd offer everyone to continue the discussion in #107

**Pull request merged**
