### PR TITLE
Remove distutils extra dependency

### PR DESCRIPTION
**Pull request by cydanil**
@kirienko ,

This PR aims to remove the dependency on `DistUtilsExtra`.
That library, although well-intentioned, is a bit awkward to install across systems. 
Removing it would also facilitate the development and testing in virtual environments.

I also took the liberty to flake that file a bit.

### CODE REVIEW

**Comment by kirienko** [comment]
Cool, I was just about to open an issue about that. I'm dreaming about getting rid of system python libraries, because they complicate CI machinery a lot. (I suspect that it's also possible to get `GObject` and `Pango` from `pip`, but we will need to build them from source code).

I avoid to touch formatting for the time being. Yeah, man, that's hard and my eyes are bleeding, but it's easy to bring new bugs with that while our tests are broken or missing. So be careful with that!

Many-many thanks for your help!

**Comment by cydanil** [comment]
Thanks for the feedback, I'll keep my hands away from `flake8`. 
Before resolving the WIP status, I'd like to confirm that this still builds the the packages as indented.

**Comment by kirienko** [comment]
The building from `master` on Github Actions is currently broken right because of that python dependencies. The thing is that Actions live in their own virtual environments and they don't see python packages of the system. 

Previously in Travis I worked around that fact by taking a special version of Ubuntu (`bionic`) which has `python3.6` by default and deriving virtual env from that. It worked then only for `py36`. Here you can [redefine PYTHONPATH](https://github.community/t5/GitHub-Actions/Set-pythonpath-in-Github-Actions-running-on-Ubuntu/td-p/51226) if you want (feel free to do that). Alternatively, as I said, you may take `pygobject` and `pycairo` (already in the `requirements.txt`) from `pip` and ask CI to build them on the fly.

**Comment by cydanil** [comment]
I can confirm that I can generate the distribution fine (on Linux Mint).  
I tried on Windows, but it's not trivial (GTK3 support on Windows is not straightforward).  

Note that as this project is using `distutils` and not `setuptools`, the tarball is created using:
```bash
python setup.py sdist
```
I suggest to add to `.github/workflow/build.yml` the above command.

**Comment by kirienko** [comment]
Just do it!

I'm not sure that Windows build worked in the last couple of years :)
And I have no working Windows machine to test. You may add a building scenario for Windows as well.

**Comment by kirienko** [comment]
And BTW I have nothing against switching to `setuptools` if you're up to. I might be wrong, but it looks like as soon as you get rid of `DistUtilsExtra`, it shouldn't be a big problem any more. I'm not fully understand if we can benefit from that, but why not.

**Comment by cydanil** [comment]
It's something for another PR, I reckon.

**Comment by kirienko** [comment]
@cydanil There's a pending invitation for you to become a _collaborator_. (I guess somewhere in you emails or in the Github notifications.) Check out and get your rights :genie: 

image

**Comment by kirienko** [comment]
Hurray!

It's strange that the [build](https://github.com/kirienko/gourmet/runs/637745556) has failed:
```
    running build_i18n
    error: error in setup.cfg: command 'build_i18n' has no such option 'domain'
```

**Comment by cydanil** [comment]
I saw it, I'll have it fixed later today

**Pull request merged**
