### PR TITLE
Fix: migrate old gtk imports to GTK 3 imports

### PR DESCRIPTION
**Pull request by saxon-s**
The GTK imports in some plugin modules were not converted to GTK 3 imports.
This change adds the required Gtk, Gdk, GObject and Pango imports and removes unused gtk or gobject imports.

### CODE REVIEW

**Review by cydanil — CHANGES_REQUESTED** [review]
Neat, thanks!

If I may nitpick, would it be possible to have the `gi.repository` imports on a single line, in alphabetical order? Such as this:

```python
from gi.repository import Gdk, Gtk, GObject, Pango
```

Thank you!

**Comment by saxon-s** [comment]
No problem, I will resubmit the imports on a single line. I basically followed the same style as the recently add gi.repository imports. I will raise another PR to change all gi.repository imports to follow the single line style so that we have consistency.

BTW, alphabetical order is:
`from gi.repository import Gdk, GObject, Gtk, Pango`

**Review by cydanil — APPROVED** [review]
Thanks for taking the time to go through it!
As for myself, it's back to kindergarten for a while...

**Comment by saxon-s** [comment]
It also confused me as well ... visually, lower case 't' is smaller than upper case 'O' which tricks the brain.

**Pull request merged**
