### PR TITLE
Run tests in XVFB on Github actions

### LINKED ISSUE #37: Adding xvfb-run to test CI runner
I'm now working on fixing `test_reccard.py`, and it does loads of Gtk operations, one of which is to launch a window. This may not work nicely in the CI, where there's no X server.

I'm not there yet, but I will be facing this issue.

I suggest we follow the [PyGObject docs on CI](https://pygobject.readthedocs.io/en/latest/guide/testing.html#testing-and-continuous-integration), and add `xvfb-run` to the CI.

(`xvfb-run` has been superseeded by `xorg-xf86-video-dummy`, but I don't know enough to make an informed suggestion.)

That's indeed adding a dependency, but would be required only within the `test` CI runner.

### PR DESCRIPTION
**Pull request by takluyver**
Closes gh-37

### CODE REVIEW

**Comment by takluyver** [comment]
I solved the hang by skipping a test. But I don't know quite what it's meant to test - it just launches the GUI and waits until you close it interactively (which you can't do when it's running in Xvfb). It doesn't assert anything.

My best guess is that the developer is meant to manually check that the sample recipes for the other tests have been added correctly. Manual checks don't really make sense in CI.

**Comment by takluyver** [comment]
It appears that the default timeout on Github actions is 6 hours! Nice if you have a long-running build, I guess.

**Comment by cydanil** [comment]
Thanks for the PR, I tried running it, but I'm getting message saying that my workflow has been cancelled. I'll dig into that later (could it be fair use?)

**Comment by takluyver** [comment]
Oh, I'm not even sure how to run the workflow manually. But it's run automatically on the pull request:
https://github.com/kirienko/gourmet/pull/81/checks?check_run_id=692008915

**Comment by cydanil** [comment]
Yes, thanks! I meant I tried it with my tests. I hadn't noticed that we were already installing `xvfb`... so that's an LGTM here, and now to see what we can do about using the latest Ubuntu within the action.

thanks a lot! :)

**Pull request merged**
