### PR TITLE
Create message.txt

### PR DESCRIPTION
**Pull request by toddobryan**
This is the only way I could think of to contact you!

### CODE REVIEW

**Comment by kirienko** [comment]
Hey @toddobryan, that's neat!

**Comment by toddobryan** [comment]
So, is there anything I can do to help and how should we communicate?

**Comment by kirienko** [comment]
I would really appreciate your help, but right now I cannot figure out what to start with. Gourmet is a good software, but nowadays it looks like an abandoned house with rusty pipes and roof that could crash down from a single touch. And if you want to fix that particular piece of a pipe, you cannot just change it for a new one, because pipes of that diameter were out of stock ten years ago already.

Some time ago @maweki did a great step towards `python3`. But since then things have changed, and I had to fix some other stuff too. Eventually, I can start the GUI. But I cannot go any further. 

Then I thought that it'd be nice to have some testing system working for everyone.  But that looks like a separate tangle of problems. Because there was no `setuptools` at the time Gourmet emerged.

Then, if we had working CI, we can do changes in much easier... That's kinda road map.
I can merge my changes in a cleaner way (I didn't expect anyone cares) to my master and you can pull and see what you can do.

I'm really happy that someone needs this working too! Together we can fix things faster!

And regarding communication... I would say that Github provides a reasonably good communication interface (issues, pull requests, comments to commits and to the code itself). Were are talking, aren't we? :)

**Comment by toddobryan** [comment]
Sounds good. I think you'll need to turn on issues for the repo, though. The original Gourmet used a different issue reporter.

If you come across something that you could use help with, let me know. As I said, I don't have a lot of experience with Python3, but I'm willing to learn.

**Comment by maweki** [comment]
First of all, good work on taking over my one-cold-weekend-fiddling. I have a few questions:

* How do we want to bring py3 to gourmet? I was thinking of starting with touching as little code as possible and just changing the gtk3.
* How are we going to coordinate the work? That the Issue tracking is disabled in this repository has been mentioned by @toddobryan 
* How is the code going to flow back into the project? Are they honoring Pull Requests? Are any of the maintainers still alive?

Also, the CI is not really working. There seem to be some issues with `pip` (I am not a good devops-person). I tried out the current branch and it errored out the following way (with a "problem adding row" debug output before):

```
Traceback (most recent call last):
  File "bin/gourmet", line 17, in <module>
    GourmetRecipeManager.startGUI()
  File "./gourmet/GourmetRecipeManager.py", line 704, in startGUI
    r=RecGui(splash_label=splash.label)
  File "./gourmet/GourmetRecipeManager.py", line 924, in __init__
    editable=False)
  File "./gourmet/recindex.py", line 65, in __init__
    self.setup_widgets()
  File "./gourmet/recindex.py", line 106, in setup_widgets
    self.setup_rectree()
  File "./gourmet/recindex.py", line 222, in setup_rectree
    self.create_rmodel(self.rvw)
  File "./gourmet/recindex.py", line 217, in create_rmodel
    self.rmodel = RecipeModel(vw,self.rd,per_page=self.prefs.get('recipes_per_page',12))
  File "./gourmet/recindex.py", line 663, in __init__
    per_page=per_page)
  File "./gourmet/gtk_extras/pageable_store.py", line 323, in __init__
    per_page=per_page)
  File "./gourmet/gtk_extras/pageable_store.py", line 50, in __init__
    self.update_tree()
  File "./gourmet/gtk_extras/pageable_store.py", line 158, in update_tree
    self.append(row)
  File "/usr/lib64/python3.7/site-packages/gi/overrides/Gtk.py", line 995, in append
    return self._do_insert(-1, row)
  File "/usr/lib64/python3.7/site-packages/gi/overrides/Gtk.py", line 986, in _do_insert
    row, columns = self._convert_row(row)
  File "/usr/lib64/python3.7/site-packages/gi/overrides/Gtk.py", line 890, in _convert_row
    raise ValueError('row sequence has the incorrect number of elements')
ValueError: row sequence has the incorrect number of elements

```

I am verry happy to investigate this, but first we have to clear up the questions on coordination.

**Comment by kirienko** [comment]
Hi all,
* I enabled Issues for this repo;
* I merged the `py3`-syntax related part  to the `master`, and one can try to start the app;
* I'd like to rename the current `python3` branch to something like `CI-configuration`, but since it was already cloned, I avoid doing this without an agreement of the community;
* Regarding the aim of this activity ("how do we bring py3"): here I agree with @maweki, I'd like
  + to have Gourmet app _running_ with python3.6+ interpreter;
  + to have a possibility to _build_ Gourmet app binary without any use of `python2`.
*  I would also try to touch as little functional code as possible until these two objectives are met. I would even sacrifice [all or almost all] the plugins during this transition phase. Having the app and CI working, we could fix it later.
* I don't know whether original maintainers are still willing to work on this project. I hope they are. We can work here, and create a pull request when we're ready. (Hey @thinkle, @ockham, greetings!) 
* But the coolest thing behind the open source approach is that we can go further by our own, even if original maintainers resigned. (My family has been actively using Gourmet for at least 10 years, and we plan to keep it going.)
* Misc:
  + CI is now working, but building is not. I'm doing my best to figure out what's wrong with `distutils`
  + I saw the problem with "incorrect number of elements", yes. I failed to fix it quickly. I suspect that the problem might be in the way Gourmet treats unicode strings now. There might be a `split()` somewhere, and doesn't work as it was intended, or something like this.
  + we can create issues for all that to discuss those topics in details.

**Comment by maweki** [comment]
This all sounds good. The question about original maintainership is because of my aversion to re-create infrastructure and stuff. Ideally, we would want to keep the existing website. We have to re-think packaging though, as the old packages will be removed from repositories as python2 is removed.

I have enabled "watching" for this whole repository and will help out where I can.

**Comment by kirienko** [comment]
Closed due to #2. Now we can start working.

**Comment by saxon-s** [comment]
Hi All, 

I am glad to finally see activity in migrating Gourmet to Python 3 and GTK+. I'm impressed with the progress this team has made so far. I like the fact that you are modernising the code as well.

A quick introduction, I became the maintainer for thinkle/gourmet by chance when the original author of Gourmet, Tom Henkle moved on to developing a new react web-app version of Gourmet. He did not have time to accept PRs and I guess he got tired of me bugging him to accept my PRs so he gave me access to do it myself. Bernie (ockham) the previous maintainer has also moved on. Bernie made the Windows releases (which I believe was not straight forward to make). He also attempted to rewrite the ORM as a MVC based architecture. 

My background is C/C++ and building telecom systems. I got involved with Gourmet as I wanted to learn Python. 

As you have no doubt seen, Gourmet has be neglected for a number of years. There are many hacks, bugs, dead code, out of date unit tests (unit tests are also scattered through out the source tree). I started cleaning up the code and fixing bugs sometime back in preparation to migrate to Python 3. It is easy to fall down rabbit holes and waste a lot of time. (I suspect this is why Tom opted to rewrite Gourmet as a React web-app). 

As this migration is a huge undertaking, I would like to collaborate with this team and (when ready) upstream the changes to the Gourmet repo. 

BTW, I've created a Slack workspace to encourage collaboration on this effort. Here is the link to join:
https://join.slack.com/t/gourmet-github/shared_invite/zt-e3t9zik1-aelzozuTMZuHGqpY~t8jUQ

Thanks.

**Comment by kirienko** [comment]
Hi @saxon-s 

I'm really glad to hear from the maintainers of original repo. I also see some activity there. I hope we will release a fully `python3` compatible Gourmet via that original repo.

Also I'd be very helpful if you can contribute to this transition, because you probably know the internals of the code base much better than such a newcomer like me!

P.S. Unfortunately I click to the Slack link too late, it has already expired.

**Comment by saxon-s** [comment]
Hi @kirienko, @cydanil, @toddobryan, @FriedrichFroebel, 

I will be happy to contribute.

I've created a new invite to join the Gourmet workspace on Slack. It should be valid for 4 week:
https://join.slack.com/t/gourmet-github/shared_invite/zt-dy3zh1cj-Th~_~3vNLXH1rU5vEbGJnw

**Pull request closed without merging**
