### PR TITLE
Revert casting epoch stamp to int in timer

### PR DESCRIPTION
**Pull request by cydanil**
This fixes a bug I introduced in #98 where the truncating of an epoch stamp makes even seconds being skipped.

That bug can be reproduced by setting the timer to any value, and watching it count down: seconds will go down as `10, 9, 7, 5, 3 ,1`.

### CODE REVIEW

**Comment by takluyver** [comment]
I'm guessing you sometimes get a time like 7.99, and `int()` always rounds down? It's [documented](https://lazka.github.io/pgi-docs/#Gtk-3.0/classes/SpinButton.html#Gtk.SpinButton.set_value) that `SpinButton.set_value()` accepts a float, so this LGTM.

**Comment by maweki** [comment]
We shouldn't re-read the spin value on every tick. It might accept float but it probably doesn't return it.

**Comment by cydanil** [comment]
`get_value` returns a float, `get_value_as_int` returns an int, and `get_text`returns a str.

The spinners values were read each time before I came in, so I didn't change it,  though I agree that it would feel nicer not to read them all the time.

**Comment by takluyver** [comment]
+1 to fixing the specific problem for now

**Comment by maweki** [comment]
merge as you like. I'll keep it in mind and maybe fix it at some point

**Comment by takluyver** [comment]
Or open an issue for it? I find my mind fills up pretty quickly. :wink:

**Comment by cydanil** [comment]
Thanks, I believe it's better to address the issue now.
I've also added a subtraction, for which I hope the in-line comments are clear.

**Comment by cydanil** [comment]
If there are no further comments, I'll merge this in this evening :)

**Comment by cydanil** [comment]
Ok, I've reduced the loop period to 100ms.

**Pull request merged**
