### PR TITLE
Don't use exceptions to create a singleton class - fix test_importManager

### LINKED ISSUE #29: Fix test_importManager.py
Like may other tests, it fails with
```
TypeError: catching classes that do not inherit from BaseException is not allowed
```
but it looks like an import problem.
Priority: medium

### PR DESCRIPTION
**Pull request by takluyver**
Closes #29

### CODE REVIEW

**Review by maweki — APPROVED** [review]
I think this looks good and is nice and clean

**Comment by takluyver** [comment]
There were a number of singleton classes using a very old pattern where the `__init__` method would raise an existing instance like an exception, and a corresponding external function would catch the exception and return it. Some of them had been updated to inherit from `BaseException`, which makes this work in Python 3, but it's a pretty ugly way to make a singleton.

I've gone for pretty soft singletons, where you call `Class.instance()` to get the single instance, but you can still call `Class()` to get an independent copy. It's possible to either prevent `Class()` entirely or override it to reuse a global instance, but I wouldn't bother without a good reason.

**Comment by takluyver** [comment]
Though interestingly, you can still read the original description of the singleton pattern using `raise` in a conference paper from 1997: https://legacy.python.org/workshops/1997-10/proceedings/savikko.html

So this was probably tested on Python 1.4!

**Comment by maweki** [comment]
I want a second pair of eyes for that decision (@cydanil @kirienko ?) but I think this way of implementing singletons is fine. I rather it is visible in the caller code, that we get the singleton. Principle of least surprise and such...

**Review by cydanil — APPROVED** [review]
yay!

I'm not familiar with what each of these classes do, however the changes are the same across all singletons (which I hadn't realised there were so many of), and are indeed a more modern implementation.

Thanks Thomas for having a go at it! :)

**Comment by maweki** [comment]
This commit throws me into an infinite loop on startup

**Comment by maweki** [comment]
There's a loop between `ExportManager.instance()` and `RecGui.instance()`

**Comment by takluyver** [comment]
Sorry about that, I was focused on running the tests. I'll take a look; I don't think it's actually hard to break those cycles.

**Pull request merged**
